# Form implementation generated from reading ui file 'ui_files_latest/Page9_Share_qwidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from resources_rc import *
main_page_image = ":images/BEST_landing_abstract.png"
side_page_image = ":images/BEST_side_abstract.png"


class Ui_Page9_Share(object):
    def setupUi(self, Page9_Share):
        Page9_Share.setObjectName("Page9_Share")
        Page9_Share.resize(1260, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Page9_Share.sizePolicy().hasHeightForWidth())
        Page9_Share.setSizePolicy(sizePolicy)
        Page9_Share.setStyleSheet("")
        self.layoutWidget = QtWidgets.QWidget(parent=Page9_Share)
        self.layoutWidget.setGeometry(QtCore.QRect(190, 650, 1051, 35))
        self.layoutWidget.setObjectName("layoutWidget")
        self.button_layout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.button_layout.setContentsMargins(0, 0, 0, 0)
        self.button_layout.setObjectName("button_layout")
        self.backBtn = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.backBtn.setObjectName("backBtn")
        self.button_layout.addWidget(self.backBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.button_layout.addItem(spacerItem)
        self.saveBtn = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.saveBtn.setObjectName("saveBtn")
        self.button_layout.addWidget(self.saveBtn)
        self.nextBtn = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setKerning(True)
        self.nextBtn.setFont(font)
        self.nextBtn.setObjectName("nextBtn")
        self.button_layout.addWidget(self.nextBtn)
        self.fuel_switching_group = QtWidgets.QGroupBox(parent=Page9_Share)
        self.fuel_switching_group.setGeometry(QtCore.QRect(200, 80, 1001, 241))
        font = QtGui.QFont()
        font.setBold(True)
        self.fuel_switching_group.setFont(font)
        self.fuel_switching_group.setStyleSheet("QPushButton {\n"
"    background-color: #26481f;  /* Green */\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"    border-radius: 6px;\n"
"    min-width: 90px;\n"
"    min-height: 15px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3e8e41;\n"
"}\n"
"\n"
"QPushButton#saveBtn {\n"
"                background-color: white;\n"
"                color: #26481f;\n"
"            }\n"
"QPushButton#saveBtn:hover {\n"
"                background-color: #45a049;\n"
"              color: white;\n"
"            }\n"
"\n"
"    QLineEdit {\n"
"        border-radius: 10px;    \n"
"        padding: 5px;           \n"
"    }\n"
"\n"
"myLineEdit->setFixedSize(200, 30)")
        self.fuel_switching_group.setObjectName("fuel_switching_group")
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.fuel_switching_group)
        self.layoutWidget1.setGeometry(QtCore.QRect(367, 40, 261, 182))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.fuel_switching_gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.fuel_switching_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.fuel_switching_gridLayout.setObjectName("fuel_switching_gridLayout")
        self.coal_label_page9 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.coal_label_page9.setObjectName("coal_label_page9")
        self.fuel_switching_gridLayout.addWidget(self.coal_label_page9, 0, 0, 1, 1)
        self.coal_input_page9 = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coal_input_page9.sizePolicy().hasHeightForWidth())
        self.coal_input_page9.setSizePolicy(sizePolicy)
        self.coal_input_page9.setText("")
        self.coal_input_page9.setObjectName("coal_input_page9")
        self.fuel_switching_gridLayout.addWidget(self.coal_input_page9, 0, 1, 1, 1)
        self.coke_label_page9 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.coke_label_page9.setObjectName("coke_label_page9")
        self.fuel_switching_gridLayout.addWidget(self.coke_label_page9, 1, 0, 1, 1)
        self.coke_input_page9 = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coke_input_page9.sizePolicy().hasHeightForWidth())
        self.coke_input_page9.setSizePolicy(sizePolicy)
        self.coke_input_page9.setText("")
        self.coke_input_page9.setObjectName("coke_input_page9")
        self.fuel_switching_gridLayout.addWidget(self.coke_input_page9, 1, 1, 1, 1)
        self.natural_gas_label_page9 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.natural_gas_label_page9.setObjectName("natural_gas_label_page9")
        self.fuel_switching_gridLayout.addWidget(self.natural_gas_label_page9, 2, 0, 1, 1)
        self.natural_gas_input_page9 = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.natural_gas_input_page9.sizePolicy().hasHeightForWidth())
        self.natural_gas_input_page9.setSizePolicy(sizePolicy)
        self.natural_gas_input_page9.setText("")
        self.natural_gas_input_page9.setObjectName("natural_gas_input_page9")
        self.fuel_switching_gridLayout.addWidget(self.natural_gas_input_page9, 2, 1, 1, 1)
        self.biomass_label_page9 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.biomass_label_page9.setObjectName("biomass_label_page9")
        self.fuel_switching_gridLayout.addWidget(self.biomass_label_page9, 3, 0, 1, 1)
        self.biomass_input_page9 = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.biomass_input_page9.sizePolicy().hasHeightForWidth())
        self.biomass_input_page9.setSizePolicy(sizePolicy)
        self.biomass_input_page9.setText("")
        self.biomass_input_page9.setObjectName("biomass_input_page9")
        self.fuel_switching_gridLayout.addWidget(self.biomass_input_page9, 3, 1, 1, 1)
        self.msw_label_page9 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.msw_label_page9.setObjectName("msw_label_page9")
        self.fuel_switching_gridLayout.addWidget(self.msw_label_page9, 4, 0, 1, 1)
        self.msw_input_page9 = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msw_input_page9.sizePolicy().hasHeightForWidth())
        self.msw_input_page9.setSizePolicy(sizePolicy)
        self.msw_input_page9.setText("")
        self.msw_input_page9.setObjectName("msw_input_page9")
        self.fuel_switching_gridLayout.addWidget(self.msw_input_page9, 4, 1, 1, 1)
        self.renewable_energy_group = QtWidgets.QGroupBox(parent=Page9_Share)
        self.renewable_energy_group.setGeometry(QtCore.QRect(200, 330, 1001, 91))
        font = QtGui.QFont()
        font.setBold(True)
        self.renewable_energy_group.setFont(font)
        self.renewable_energy_group.setObjectName("renewable_energy_group")
        self.layoutWidget2 = QtWidgets.QWidget(parent=self.renewable_energy_group)
        self.layoutWidget2.setGeometry(QtCore.QRect(200, 40, 561, 30))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.renewable_formLayout = QtWidgets.QFormLayout(self.layoutWidget2)
        self.renewable_formLayout.setContentsMargins(0, 0, 0, 0)
        self.renewable_formLayout.setObjectName("renewable_formLayout")
        self.share_electricity_label_page9 = QtWidgets.QLabel(parent=self.layoutWidget2)
        self.share_electricity_label_page9.setObjectName("share_electricity_label_page9")
        self.renewable_formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.share_electricity_label_page9)
        self.share_electricity_input_page9 = QtWidgets.QLineEdit(parent=self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.share_electricity_input_page9.sizePolicy().hasHeightForWidth())
        self.share_electricity_input_page9.setSizePolicy(sizePolicy)
        self.share_electricity_input_page9.setText("")
        self.share_electricity_input_page9.setObjectName("share_electricity_input_page9")
        self.renewable_formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.share_electricity_input_page9)
        self.side_image = QtWidgets.QLabel(parent=Page9_Share)
        self.side_image.setGeometry(QtCore.QRect(0, -30, 171, 761))
        self.side_image.setText("")
        self.side_image.setPixmap(QtGui.QPixmap(side_page_image))
        self.side_image.setObjectName("side_image")
        self.progressBar = QtWidgets.QProgressBar(parent=Page9_Share)
        self.progressBar.setGeometry(QtCore.QRect(200, 20, 1001, 23))
        self.progressBar.setFixedHeight(12)
        self.progressBar.setTextVisible(False)
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    background-color: #F0F0F0;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"QProgressBar::chunk {\n"
"    border-radius: 5px;\n"
"    background: QLinearGradient(\n"
"        x1: 0, y1: 0, x2: 1, y2: 0,\n"
"        stop: 0 #33bef0,   /* Light Blue */\n"
"        stop: 1 #77d695    /* Light Green */\n"
"    );\n"
"}")
        self.progressBar.setProperty("value", 82)
        self.progressBar.setObjectName("progressBar")
        self.layoutWidget_3 = QtWidgets.QWidget(parent=Page9_Share)
        self.layoutWidget_3.setGeometry(QtCore.QRect(200, 40, 1001, 16))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_12.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_12.addWidget(self.label_10, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_12.addWidget(self.label_11, 0, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_12.addWidget(self.label_12, 0, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_12.addWidget(self.label_13, 0, 4, 1, 1)
        self.label_14 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_12.addWidget(self.label_14, 0, 5, 1, 1)
        self.label_15 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_12.addWidget(self.label_15, 0, 6, 1, 1)
        self.label_16 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_12.addWidget(self.label_16, 0, 7, 1, 1)

        self.retranslateUi(Page9_Share)
        QtCore.QMetaObject.connectSlotsByName(Page9_Share)

    def retranslateUi(self, Page9_Share):
        _translate = QtCore.QCoreApplication.translate
        Page9_Share.setWindowTitle(_translate("Page9_Share", "Form"))
        self.backBtn.setText(_translate("Page9_Share", "Back"))
        self.saveBtn.setText(_translate("Page9_Share", "Save Progress"))
        self.nextBtn.setText(_translate("Page9_Share", "Next"))
        self.fuel_switching_group.setTitle(_translate("Page9_Share", "New Fuel Share (%)"))
        self.coal_label_page9.setText(_translate("Page9_Share", "Coal"))
        self.coke_label_page9.setText(_translate("Page9_Share", "Coke"))
        self.natural_gas_label_page9.setText(_translate("Page9_Share", "Natural Gas"))
        self.biomass_label_page9.setText(_translate("Page9_Share", "Biomass"))
        self.msw_label_page9.setText(_translate("Page9_Share", "Municipal Wastes"))
        self.renewable_energy_group.setTitle(_translate("Page9_Share", "Renewable Energy (%)"))
        self.share_electricity_label_page9.setText(_translate("Page9_Share", "Share of electricity from purchased or self-generated renewable "))
        self.label_3.setText(_translate("Page9_Share", "Cost and Emission"))
        self.label_10.setText(_translate("Page9_Share", "Production"))
        self.label_11.setText(_translate("Page9_Share", "Electricity Generation            "))
        self.label_12.setText(_translate("Page9_Share", "Energy Input"))
        self.label_13.setText(_translate("Page9_Share", "Target"))
        self.label_14.setText(_translate("Page9_Share", "EE Measures"))
        self.label_15.setText(_translate("Page9_Share", "Fuel Switching"))
        self.label_16.setText(_translate("Page9_Share", "Other Measures"))
