# Form implementation generated from reading ui file 'ui_files_latest/Page0_LandingPage_qwidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from resources_rc import *
main_page_image = ":images/BEST_landing_abstract.png"
side_page_image = ":images/BEST_side_abstract.png"

class Ui_LandingPage(object):
    def setupUi(self, LandingPage):
        LandingPage.setObjectName("LandingPage")
        LandingPage.resize(1260, 700)
        LandingPage.setStyleSheet("QPushButton {\n"
"    background-color: white; \n"
"    color: #00313c;\n"
"    border: none;\n"
"    padding-top: 11px;           /* Add vertical padding */\n"
"    padding-bottom: 8px;        /* Match top */\n"
"    padding-left: 16px;\n"
"    padding-right: 16px;\n"
"    font-size: 17px;      \n"
"    text-align: center;\n"
"    border-radius: 16px;\n"
"    min-width: 100px;\n"
"    min-height: 20px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(232, 232, 232);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4aac4e;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#resumeBtn {\n"
"                background-color: white;\n"
"                color: #00313c;\n"
"            }\n"
"QPushButton#resumeBtn:hover {\n"
"                background-color: #007681;\n"
"              color: white;\n"
"            }\n"
"\n"
"    QLineEdit {\n"
"        border-radius: 10px;    \n"
"        padding: 5px;           \n"
"    }\n"
"\n"
"myLineEdit->setFixedSize(200, 30)")
        self.label = QtWidgets.QLabel(parent=LandingPage)
        self.label.setGeometry(QtCore.QRect(0, 0, 1260, 700))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(main_page_image))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=LandingPage)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(260, 530, 731, 61))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.get_started = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("ITC Franklin Gothic LT Pro")
        font.setPointSize(-1)
        self.get_started.setFont(font)
        self.get_started.setStyleSheet("QPushButton#get_started {\n"
"        background-color: #00313c;  /* Dark Blue */\n"
"        color: white;\n"
"    }\n"
"\n"
"QPushButton#get_started:hover {\n"
"        background-color: #45a049;\n"
"        color: white;\n"
"    }\n"
"\n"
"QPushButton#get_started:pressed {\n"
"        background-color: #3e8e41;\n"
"    }")
        self.get_started.setObjectName("get_started")
        self.gridLayout.addWidget(self.get_started, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.resumeBtn = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("ITC Franklin Gothic LT Pro")
        font.setPointSize(-1)
        self.resumeBtn.setFont(font)
        self.resumeBtn.setStyleSheet("")
        self.resumeBtn.setObjectName("resumeBtn")
        self.gridLayout.addWidget(self.resumeBtn, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)

        self.retranslateUi(LandingPage)
        QtCore.QMetaObject.connectSlotsByName(LandingPage)

    def retranslateUi(self, LandingPage):
        _translate = QtCore.QCoreApplication.translate
        LandingPage.setWindowTitle(_translate("LandingPage", "Form"))
        self.get_started.setText(_translate("LandingPage", "Get Started"))
        self.resumeBtn.setText(_translate("LandingPage", "Resume"))
