# Form implementation generated from reading ui file 'ui_files_latest/Page4_CarbonCapture_qwidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from resources_rc import *
main_page_image = ":images/BEST_landing_abstract.png"
side_page_image = ":images/BEST_side_abstract.png"


class Ui_Page4_CarbonCapture(object):
    def setupUi(self, Page4_CarbonCapture):
        Page4_CarbonCapture.setObjectName("Page4_CarbonCapture")
        Page4_CarbonCapture.resize(1260, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Page4_CarbonCapture.sizePolicy().hasHeightForWidth())
        Page4_CarbonCapture.setSizePolicy(sizePolicy)
        Page4_CarbonCapture.setStyleSheet("")
        self.layoutWidget = QtWidgets.QWidget(parent=Page4_CarbonCapture)
        self.layoutWidget.setGeometry(QtCore.QRect(190, 650, 1051, 35))
        self.layoutWidget.setObjectName("layoutWidget")
        self.button_layout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.button_layout.setContentsMargins(0, 0, 0, 0)
        self.button_layout.setObjectName("button_layout")
        self.backBtn = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.backBtn.setObjectName("backBtn")
        self.button_layout.addWidget(self.backBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.button_layout.addItem(spacerItem)
        self.saveBtn = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.saveBtn.setObjectName("saveBtn")
        self.button_layout.addWidget(self.saveBtn)
        self.nextBtn = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setKerning(True)
        self.nextBtn.setFont(font)
        self.nextBtn.setObjectName("nextBtn")
        self.button_layout.addWidget(self.nextBtn)
        self.clinker_material_group = QtWidgets.QGroupBox(parent=Page4_CarbonCapture)
        self.clinker_material_group.setGeometry(QtCore.QRect(210, 90, 1001, 81))
        font = QtGui.QFont()
        font.setBold(True)
        self.clinker_material_group.setFont(font)
        self.clinker_material_group.setStyleSheet("QPushButton {\n"
"    background-color: #26481f;  /* Green */\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"    border-radius: 6px;\n"
"    min-width: 90px;\n"
"    min-height: 15px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3e8e41;\n"
"}\n"
"\n"
"QPushButton#saveBtn {\n"
"                background-color: white;\n"
"                color: #26481f;\n"
"            }\n"
"QPushButton#saveBtn:hover {\n"
"                background-color: #45a049;\n"
"              color: white;\n"
"            }\n"
"\n"
"    QLineEdit {\n"
"        border-radius: 10px;    \n"
"        padding: 5px;           \n"
"    }\n"
"\n"
"myLineEdit->setFixedSize(200, 30)")
        self.clinker_material_group.setObjectName("clinker_material_group")
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.clinker_material_group)
        self.layoutWidget1.setGeometry(QtCore.QRect(280, 30, 401, 41))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.formLayout_carbon_capture = QtWidgets.QFormLayout(self.layoutWidget1)
        self.formLayout_carbon_capture.setContentsMargins(0, 0, 0, 0)
        self.formLayout_carbon_capture.setObjectName("formLayout_carbon_capture")
        self.co2_captured_label = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.co2_captured_label.setObjectName("co2_captured_label")
        self.formLayout_carbon_capture.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.co2_captured_label)
        self.co2_captured_input = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.co2_captured_input.sizePolicy().hasHeightForWidth())
        self.co2_captured_input.setSizePolicy(sizePolicy)
        self.co2_captured_input.setText("")
        self.co2_captured_input.setObjectName("co2_captured_input")
        self.formLayout_carbon_capture.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.co2_captured_input)
        self.side_image = QtWidgets.QLabel(parent=Page4_CarbonCapture)
        self.side_image.setGeometry(QtCore.QRect(0, -30, 171, 761))
        self.side_image.setText("")
        self.side_image.setPixmap(QtGui.QPixmap(side_page_image))
        self.side_image.setObjectName("side_image")
        self.progressBar = QtWidgets.QProgressBar(parent=Page4_CarbonCapture)
        self.progressBar.setGeometry(QtCore.QRect(200, 20, 1001, 23))
        self.progressBar.setFixedHeight(12)
        self.progressBar.setTextVisible(False)
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    background-color: #F0F0F0;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"QProgressBar::chunk {\n"
"    border-radius: 5px;\n"
"    background: QLinearGradient(\n"
"        x1: 0, y1: 0, x2: 1, y2: 0,\n"
"        stop: 0 #33bef0,   /* Light Blue */\n"
"        stop: 1 #77d695    /* Light Green */\n"
"    );\n"
"}")
        self.progressBar.setProperty("value", 22)
        self.progressBar.setObjectName("progressBar")
        self.layoutWidget_2 = QtWidgets.QWidget(parent=Page4_CarbonCapture)
        self.layoutWidget_2.setGeometry(QtCore.QRect(200, 40, 1001, 16))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_11.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_11.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_11.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_11.addWidget(self.label_5, 0, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_11.addWidget(self.label_6, 0, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_11.addWidget(self.label_7, 0, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_11.addWidget(self.label_8, 0, 6, 1, 1)
        self.label_9 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_11.addWidget(self.label_9, 0, 7, 1, 1)

        self.retranslateUi(Page4_CarbonCapture)
        QtCore.QMetaObject.connectSlotsByName(Page4_CarbonCapture)

    def retranslateUi(self, Page4_CarbonCapture):
        _translate = QtCore.QCoreApplication.translate
        Page4_CarbonCapture.setWindowTitle(_translate("Page4_CarbonCapture", "Form"))
        self.backBtn.setText(_translate("Page4_CarbonCapture", "Back"))
        self.saveBtn.setText(_translate("Page4_CarbonCapture", "Save Progress"))
        self.nextBtn.setText(_translate("Page4_CarbonCapture", "Next"))
        self.clinker_material_group.setTitle(_translate("Page4_CarbonCapture", "Carbon Capture"))
        self.co2_captured_label.setText(_translate("Page4_CarbonCapture", "CO2 Captured (million metric tons/year)"))
        self.label.setText(_translate("Page4_CarbonCapture", "Cost and Emission"))
        self.label_2.setText(_translate("Page4_CarbonCapture", "Production"))
        self.label_4.setText(_translate("Page4_CarbonCapture", "Electricity Generation            "))
        self.label_5.setText(_translate("Page4_CarbonCapture", "Energy Input"))
        self.label_6.setText(_translate("Page4_CarbonCapture", "Target"))
        self.label_7.setText(_translate("Page4_CarbonCapture", "EE Measures"))
        self.label_8.setText(_translate("Page4_CarbonCapture", "Fuel Switching"))
        self.label_9.setText(_translate("Page4_CarbonCapture", "Other Measures"))
