# Form implementation generated from reading ui file 'ui_files_latest/Page3_ProductionInput_qwidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from resources_rc import *
main_page_image = ":images/BEST_landing_abstract.png"
side_page_image = ":images/BEST_side_abstract.png"       


class Ui_Page3_ProductionInput(object):
    def setupUi(self, Page3_ProductionInput):
        Page3_ProductionInput.setObjectName("Page3_ProductionInput")
        Page3_ProductionInput.resize(1260, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Page3_ProductionInput.sizePolicy().hasHeightForWidth())
        Page3_ProductionInput.setSizePolicy(sizePolicy)
        Page3_ProductionInput.setStyleSheet("")
        self.layoutWidget = QtWidgets.QWidget(parent=Page3_ProductionInput)
        self.layoutWidget.setGeometry(QtCore.QRect(190, 650, 1051, 35))
        self.layoutWidget.setObjectName("layoutWidget")
        self.button_layout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.button_layout.setContentsMargins(0, 0, 0, 0)
        self.button_layout.setObjectName("button_layout")
        self.backBtn = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.backBtn.setObjectName("backBtn")
        self.button_layout.addWidget(self.backBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.button_layout.addItem(spacerItem)
        self.saveBtn = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.saveBtn.setObjectName("saveBtn")
        self.button_layout.addWidget(self.saveBtn)
        self.nextBtn = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setKerning(True)
        self.nextBtn.setFont(font)
        self.nextBtn.setObjectName("nextBtn")
        self.button_layout.addWidget(self.nextBtn)
        self.clinker_material_group = QtWidgets.QGroupBox(parent=Page3_ProductionInput)
        self.clinker_material_group.setGeometry(QtCore.QRect(210, 110, 1001, 191))
        font = QtGui.QFont()
        font.setBold(True)
        self.clinker_material_group.setFont(font)
        self.clinker_material_group.setStyleSheet("QPushButton {\n"
"    background-color: #26481f;  /* Green */\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"    border-radius: 6px;\n"
"    min-width: 90px;\n"
"    min-height: 15px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3e8e41;\n"
"}\n"
"\n"
"QPushButton#saveBtn {\n"
"                background-color: white;\n"
"                color: #26481f;\n"
"            }\n"
"QPushButton#saveBtn:hover {\n"
"                background-color: #45a049;\n"
"              color: white;\n"
"            }\n"
"\n"
"    QLineEdit {\n"
"        border-radius: 10px;    \n"
"        padding: 5px;           \n"
"    }\n"
"\n"
"myLineEdit->setFixedSize(200, 30)")
        self.clinker_material_group.setObjectName("clinker_material_group")
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.clinker_material_group)
        self.layoutWidget1.setGeometry(QtCore.QRect(170, 30, 271, 144))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.formLayout_clinker_material_1 = QtWidgets.QFormLayout(self.layoutWidget1)
        self.formLayout_clinker_material_1.setContentsMargins(0, 0, 0, 0)
        self.formLayout_clinker_material_1.setObjectName("formLayout_clinker_material_1")
        self.limestone_input = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.limestone_input.sizePolicy().hasHeightForWidth())
        self.limestone_input.setSizePolicy(sizePolicy)
        self.limestone_input.setText("")
        self.limestone_input.setObjectName("limestone_input")
        self.formLayout_clinker_material_1.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.limestone_input)
        self.gypsum_label = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.gypsum_label.setObjectName("gypsum_label")
        self.formLayout_clinker_material_1.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.gypsum_label)
        self.gypsum_input = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gypsum_input.sizePolicy().hasHeightForWidth())
        self.gypsum_input.setSizePolicy(sizePolicy)
        self.gypsum_input.setText("")
        self.gypsum_input.setObjectName("gypsum_input")
        self.formLayout_clinker_material_1.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.gypsum_input)
        self.calcined_clay_label = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.calcined_clay_label.setObjectName("calcined_clay_label")
        self.formLayout_clinker_material_1.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.calcined_clay_label)
        self.calcined_clay_input = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calcined_clay_input.sizePolicy().hasHeightForWidth())
        self.calcined_clay_input.setSizePolicy(sizePolicy)
        self.calcined_clay_input.setText("")
        self.calcined_clay_input.setObjectName("calcined_clay_input")
        self.formLayout_clinker_material_1.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.calcined_clay_input)
        self.blast_furnace_slag_label = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.blast_furnace_slag_label.setObjectName("blast_furnace_slag_label")
        self.formLayout_clinker_material_1.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.blast_furnace_slag_label)
        self.blast_furnace_slag_input = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blast_furnace_slag_input.sizePolicy().hasHeightForWidth())
        self.blast_furnace_slag_input.setSizePolicy(sizePolicy)
        self.blast_furnace_slag_input.setText("")
        self.blast_furnace_slag_input.setObjectName("blast_furnace_slag_input")
        self.formLayout_clinker_material_1.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.blast_furnace_slag_input)
        self.limestone_label = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.limestone_label.setObjectName("limestone_label")
        self.formLayout_clinker_material_1.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.limestone_label)
        self.layoutWidget2 = QtWidgets.QWidget(parent=self.clinker_material_group)
        self.layoutWidget2.setGeometry(QtCore.QRect(480, 30, 311, 111))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.other_slag_label = QtWidgets.QLabel(parent=self.layoutWidget2)
        self.other_slag_label.setObjectName("other_slag_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.other_slag_label)
        self.other_slag_input = QtWidgets.QLineEdit(parent=self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.other_slag_input.sizePolicy().hasHeightForWidth())
        self.other_slag_input.setSizePolicy(sizePolicy)
        self.other_slag_input.setText("")
        self.other_slag_input.setObjectName("other_slag_input")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.other_slag_input)
        self.fly_ash_label = QtWidgets.QLabel(parent=self.layoutWidget2)
        self.fly_ash_label.setObjectName("fly_ash_label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.fly_ash_label)
        self.fly_ash_input = QtWidgets.QLineEdit(parent=self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fly_ash_input.sizePolicy().hasHeightForWidth())
        self.fly_ash_input.setSizePolicy(sizePolicy)
        self.fly_ash_input.setText("")
        self.fly_ash_input.setObjectName("fly_ash_input")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.fly_ash_input)
        self.natural_pozzolans_label = QtWidgets.QLabel(parent=self.layoutWidget2)
        self.natural_pozzolans_label.setObjectName("natural_pozzolans_label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.natural_pozzolans_label)
        self.natural_pozzolans_input = QtWidgets.QLineEdit(parent=self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.natural_pozzolans_input.sizePolicy().hasHeightForWidth())
        self.natural_pozzolans_input.setSizePolicy(sizePolicy)
        self.natural_pozzolans_input.setText("")
        self.natural_pozzolans_input.setObjectName("natural_pozzolans_input")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.natural_pozzolans_input)
        self.kiln_clinker_production_group = QtWidgets.QGroupBox(parent=Page3_ProductionInput)
        self.kiln_clinker_production_group.setGeometry(QtCore.QRect(210, 310, 1001, 121))
        font = QtGui.QFont()
        font.setBold(True)
        self.kiln_clinker_production_group.setFont(font)
        self.kiln_clinker_production_group.setStyleSheet("QPushButton {\n"
"    background-color: #26481f;  /* Green */\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"    border-radius: 6px;\n"
"    min-width: 90px;\n"
"    min-height: 15px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3e8e41;\n"
"}\n"
"\n"
"QPushButton#saveBtn {\n"
"                background-color: white;\n"
"                color: #26481f;\n"
"            }\n"
"QPushButton#saveBtn:hover {\n"
"                background-color: #45a049;\n"
"              color: white;\n"
"            }\n"
"\n"
"    QLineEdit {\n"
"        border-radius: 10px;    \n"
"        padding: 5px;           \n"
"    }\n"
"\n"
"myLineEdit->setFixedSize(200, 30)")
        self.kiln_clinker_production_group.setObjectName("kiln_clinker_production_group")
        self.layoutWidget_2 = QtWidgets.QWidget(parent=self.kiln_clinker_production_group)
        self.layoutWidget_2.setGeometry(QtCore.QRect(200, 40, 241, 81))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.formLayout_clinker_production_1 = QtWidgets.QFormLayout(self.layoutWidget_2)
        self.formLayout_clinker_production_1.setContentsMargins(0, 0, 0, 0)
        self.formLayout_clinker_production_1.setObjectName("formLayout_clinker_production_1")
        self.type_1_label = QtWidgets.QLabel(parent=self.layoutWidget_2)
        self.type_1_label.setObjectName("type_1_label")
        self.formLayout_clinker_production_1.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.type_1_label)
        self.type_1_input = QtWidgets.QLineEdit(parent=self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.type_1_input.sizePolicy().hasHeightForWidth())
        self.type_1_input.setSizePolicy(sizePolicy)
        self.type_1_input.setText("")
        self.type_1_input.setObjectName("type_1_input")
        self.formLayout_clinker_production_1.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.type_1_input)
        self.type_2_label = QtWidgets.QLabel(parent=self.layoutWidget_2)
        self.type_2_label.setObjectName("type_2_label")
        self.formLayout_clinker_production_1.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.type_2_label)
        self.type_2_input = QtWidgets.QLineEdit(parent=self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.type_2_input.sizePolicy().hasHeightForWidth())
        self.type_2_input.setSizePolicy(sizePolicy)
        self.type_2_input.setText("")
        self.type_2_input.setObjectName("type_2_input")
        self.formLayout_clinker_production_1.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.type_2_input)
        self.layoutWidget_3 = QtWidgets.QWidget(parent=self.kiln_clinker_production_group)
        self.layoutWidget_3.setGeometry(QtCore.QRect(480, 40, 311, 81))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.formLayout_clinker_production_2 = QtWidgets.QFormLayout(self.layoutWidget_3)
        self.formLayout_clinker_production_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_clinker_production_2.setObjectName("formLayout_clinker_production_2")
        self.production_1_label = QtWidgets.QLabel(parent=self.layoutWidget_3)
        self.production_1_label.setObjectName("production_1_label")
        self.formLayout_clinker_production_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.production_1_label)
        self.production_1_input = QtWidgets.QLineEdit(parent=self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.production_1_input.sizePolicy().hasHeightForWidth())
        self.production_1_input.setSizePolicy(sizePolicy)
        self.production_1_input.setText("")
        self.production_1_input.setObjectName("production_1_input")
        self.formLayout_clinker_production_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.production_1_input)
        self.production_2_label = QtWidgets.QLabel(parent=self.layoutWidget_3)
        self.production_2_label.setObjectName("production_2_label")
        self.formLayout_clinker_production_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.production_2_label)
        self.production_2_input = QtWidgets.QLineEdit(parent=self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.production_2_input.sizePolicy().hasHeightForWidth())
        self.production_2_input.setSizePolicy(sizePolicy)
        self.production_2_input.setText("")
        self.production_2_input.setObjectName("production_2_input")
        self.formLayout_clinker_production_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.production_2_input)
        self.cement_production_group = QtWidgets.QGroupBox(parent=Page3_ProductionInput)
        self.cement_production_group.setGeometry(QtCore.QRect(210, 440, 1001, 151))
        font = QtGui.QFont()
        font.setBold(True)
        self.cement_production_group.setFont(font)
        self.cement_production_group.setObjectName("cement_production_group")
        self.layoutWidget_4 = QtWidgets.QWidget(parent=self.cement_production_group)
        self.layoutWidget_4.setGeometry(QtCore.QRect(170, 30, 271, 106))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.formLayout_cement_production_1 = QtWidgets.QFormLayout(self.layoutWidget_4)
        self.formLayout_cement_production_1.setContentsMargins(0, 0, 0, 0)
        self.formLayout_cement_production_1.setObjectName("formLayout_cement_production_1")
        self.pure_portland_label = QtWidgets.QLabel(parent=self.layoutWidget_4)
        self.pure_portland_label.setObjectName("pure_portland_label")
        self.formLayout_cement_production_1.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.pure_portland_label)
        self.pure_portland_cement_production_input = QtWidgets.QLineEdit(parent=self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pure_portland_cement_production_input.sizePolicy().hasHeightForWidth())
        self.pure_portland_cement_production_input.setSizePolicy(sizePolicy)
        self.pure_portland_cement_production_input.setText("")
        self.pure_portland_cement_production_input.setObjectName("pure_portland_cement_production_input")
        self.formLayout_cement_production_1.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.pure_portland_cement_production_input)
        self.common_portland_label = QtWidgets.QLabel(parent=self.layoutWidget_4)
        self.common_portland_label.setObjectName("common_portland_label")
        self.formLayout_cement_production_1.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.common_portland_label)
        self.common_portland_cement_production_input = QtWidgets.QLineEdit(parent=self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.common_portland_cement_production_input.sizePolicy().hasHeightForWidth())
        self.common_portland_cement_production_input.setSizePolicy(sizePolicy)
        self.common_portland_cement_production_input.setText("")
        self.common_portland_cement_production_input.setObjectName("common_portland_cement_production_input")
        self.formLayout_cement_production_1.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.common_portland_cement_production_input)
        self.slag_cement_label = QtWidgets.QLabel(parent=self.layoutWidget_4)
        self.slag_cement_label.setObjectName("slag_cement_label")
        self.formLayout_cement_production_1.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.slag_cement_label)
        self.slag_cement_production_input = QtWidgets.QLineEdit(parent=self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slag_cement_production_input.sizePolicy().hasHeightForWidth())
        self.slag_cement_production_input.setSizePolicy(sizePolicy)
        self.slag_cement_production_input.setText("")
        self.slag_cement_production_input.setObjectName("slag_cement_production_input")
        self.formLayout_cement_production_1.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.slag_cement_production_input)
        self.layoutWidget_5 = QtWidgets.QWidget(parent=self.cement_production_group)
        self.layoutWidget_5.setGeometry(QtCore.QRect(570, 30, 221, 106))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.formLayout_cement_production_2 = QtWidgets.QFormLayout(self.layoutWidget_5)
        self.formLayout_cement_production_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_cement_production_2.setObjectName("formLayout_cement_production_2")
        self.flay_ash_label = QtWidgets.QLabel(parent=self.layoutWidget_5)
        self.flay_ash_label.setObjectName("flay_ash_label")
        self.formLayout_cement_production_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.flay_ash_label)
        self.fly_ash_cement_production_input = QtWidgets.QLineEdit(parent=self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fly_ash_cement_production_input.sizePolicy().hasHeightForWidth())
        self.fly_ash_cement_production_input.setSizePolicy(sizePolicy)
        self.fly_ash_cement_production_input.setText("")
        self.fly_ash_cement_production_input.setObjectName("fly_ash_cement_production_input")
        self.formLayout_cement_production_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.fly_ash_cement_production_input)
        self.pozzolana_label = QtWidgets.QLabel(parent=self.layoutWidget_5)
        self.pozzolana_label.setObjectName("pozzolana_label")
        self.formLayout_cement_production_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.pozzolana_label)
        self.pozzolana_cement_production_input = QtWidgets.QLineEdit(parent=self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pozzolana_cement_production_input.sizePolicy().hasHeightForWidth())
        self.pozzolana_cement_production_input.setSizePolicy(sizePolicy)
        self.pozzolana_cement_production_input.setText("")
        self.pozzolana_cement_production_input.setObjectName("pozzolana_cement_production_input")
        self.formLayout_cement_production_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.pozzolana_cement_production_input)
        self.blended_label = QtWidgets.QLabel(parent=self.layoutWidget_5)
        self.blended_label.setObjectName("blended_label")
        self.formLayout_cement_production_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.blended_label)
        self.blended_cement_production_input = QtWidgets.QLineEdit(parent=self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blended_cement_production_input.sizePolicy().hasHeightForWidth())
        self.blended_cement_production_input.setSizePolicy(sizePolicy)
        self.blended_cement_production_input.setText("")
        self.blended_cement_production_input.setObjectName("blended_cement_production_input")
        self.formLayout_cement_production_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.blended_cement_production_input)
        self.progressBar = QtWidgets.QProgressBar(parent=Page3_ProductionInput)
        self.progressBar.setGeometry(QtCore.QRect(200, 20, 1001, 23))
        self.progressBar.setFixedHeight(12)
        self.progressBar.setTextVisible(False)
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    background-color: #F0F0F0;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"QProgressBar::chunk {\n"
"    border-radius: 5px;\n"
"    background: QLinearGradient(\n"
"        x1: 0, y1: 0, x2: 1, y2: 0,\n"
"        stop: 0 #33bef0,   /* Light Blue */\n"
"        stop: 1 #77d695    /* Light Green */\n"
"    );\n"
"}")
        self.progressBar.setProperty("value", 16)
        self.progressBar.setObjectName("progressBar")
        self.side_image = QtWidgets.QLabel(parent=Page3_ProductionInput)
        self.side_image.setGeometry(QtCore.QRect(0, -30, 171, 761))
        self.side_image.setText("")
        self.side_image.setPixmap(QtGui.QPixmap(side_page_image))
        self.side_image.setObjectName("side_image")
        self.layoutWidget_6 = QtWidgets.QWidget(parent=Page3_ProductionInput)
        self.layoutWidget_6.setGeometry(QtCore.QRect(200, 40, 1001, 16))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.layoutWidget_6)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_11.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_11.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_11.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_11.addWidget(self.label_5, 0, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_11.addWidget(self.label_6, 0, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_11.addWidget(self.label_7, 0, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_11.addWidget(self.label_8, 0, 6, 1, 1)
        self.label_9 = QtWidgets.QLabel(parent=self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_11.addWidget(self.label_9, 0, 7, 1, 1)

        self.retranslateUi(Page3_ProductionInput)
        QtCore.QMetaObject.connectSlotsByName(Page3_ProductionInput)

    def retranslateUi(self, Page3_ProductionInput):
        _translate = QtCore.QCoreApplication.translate
        Page3_ProductionInput.setWindowTitle(_translate("Page3_ProductionInput", "Form"))
        self.backBtn.setText(_translate("Page3_ProductionInput", "Back"))
        self.saveBtn.setText(_translate("Page3_ProductionInput", "Save Progress"))
        self.nextBtn.setText(_translate("Page3_ProductionInput", "Next"))
        self.clinker_material_group.setTitle(_translate("Page3_ProductionInput", "Clinker Material Produced per Year (tonnes/year)"))
        self.gypsum_label.setText(_translate("Page3_ProductionInput", "Gypsum"))
        self.calcined_clay_label.setText(_translate("Page3_ProductionInput", "Calcined Clay"))
        self.blast_furnace_slag_label.setText(_translate("Page3_ProductionInput", "Blast Furnace Slag"))
        self.limestone_label.setText(_translate("Page3_ProductionInput", "Limestone"))
        self.other_slag_label.setText(_translate("Page3_ProductionInput", "Other Slag"))
        self.fly_ash_label.setText(_translate("Page3_ProductionInput", "Fly Ash"))
        self.natural_pozzolans_label.setText(_translate("Page3_ProductionInput", "Other Natural Pozzolans"))
        self.kiln_clinker_production_group.setTitle(_translate("Page3_ProductionInput", "Kiln - Clinker Production"))
        self.type_1_label.setText(_translate("Page3_ProductionInput", "Type 1 Name"))
        self.type_2_label.setText(_translate("Page3_ProductionInput", "Type 2 Name"))
        self.production_1_label.setText(_translate("Page3_ProductionInput", "Production (tonnes/year)"))
        self.production_2_label.setText(_translate("Page3_ProductionInput", "Production (tonnes/year)"))
        self.cement_production_group.setTitle(_translate("Page3_ProductionInput", "Cement Production (tonnes/year)"))
        self.pure_portland_label.setText(_translate("Page3_ProductionInput", "Pure Portland"))
        self.common_portland_label.setText(_translate("Page3_ProductionInput", "Common Portland"))
        self.slag_cement_label.setText(_translate("Page3_ProductionInput", "Slag Cement"))
        self.flay_ash_label.setText(_translate("Page3_ProductionInput", "Fly Ash"))
        self.pozzolana_label.setText(_translate("Page3_ProductionInput", "Pozzolana"))
        self.blended_label.setText(_translate("Page3_ProductionInput", "Blended"))
        self.label.setText(_translate("Page3_ProductionInput", "Cost and Emission"))
        self.label_2.setText(_translate("Page3_ProductionInput", "Production"))
        self.label_4.setText(_translate("Page3_ProductionInput", "Electricity Generation            "))
        self.label_5.setText(_translate("Page3_ProductionInput", "Energy Input"))
        self.label_6.setText(_translate("Page3_ProductionInput", "Target"))
        self.label_7.setText(_translate("Page3_ProductionInput", "EE Measures"))
        self.label_8.setText(_translate("Page3_ProductionInput", "Fuel Switching"))
        self.label_9.setText(_translate("Page3_ProductionInput", "Other Measures"))
